# Ecolit Configuration Template
# Copy this file to config.yaml and customize for your setup

# Network Discovery Settings
network:
  # Scan ranges for device discovery
  # Empty list = discovery mode (scans common ranges)
  # Specific ranges = limit scanning to these subnets
  scan_ranges: []  # Example: ["192.168.0", "192.168.1"]
  
  # ECHONET Lite protocol settings
  echonet:
    interface: "0.0.0.0"  # Network interface (0.0.0.0 = all interfaces)
    port: 3610           # ECHONET Lite standard port
    timeout: 5           # Discovery timeout in seconds
  
  # Device discovery timeouts
  discovery:
    device_timeout: 0.4      # Timeout per IP during discovery scan (seconds)
    validation_timeout: 10   # Timeout for required device validation (seconds)
    property_timeout: 3.0    # Timeout for reading device properties (seconds)
    wait_iterations: 300     # Max iterations to wait for discovery
    wait_interval: 0.01      # Sleep interval between wait iterations (seconds)

# Device Configuration
devices:
  # Required devices - application will fail if these are not found
  required:
    - name: "Solar Inverter"
      ip: "192.168.0.2"
      type: "solar"
      eojgc: 0x02      # Housing/Facility class
      eojcc: 0x79      # Solar power generation
      instance: 31     # Device instance number
      
    - name: "Storage Battery"
      ip: "192.168.0.2"
      type: "battery"
      eojgc: 0x02      # Housing/Facility class
      eojcc: 0x7D      # Storage battery
      instance: 31     # Device instance number

# Application Settings
app:
  polling_interval: 10  # Seconds between device polls
  
# EV Charging Control
ev_charging:
  enabled: false               # Enable EV charging optimization
  policy: "eco"               # Charging policy: eco, hurry, emergency
  max_amps: 20                # Maximum charging current (breaker protection)
  
  # Policy-specific settings
  eco:
    export_threshold: 50      # Minimum grid export (W) before increasing amps
  hurry:
    max_import: 1000         # Maximum grid import allowed (W)
  
  # Rate limiting
  adjustment_interval: 30     # Seconds between amp adjustments  
  measurement_interval: 10    # Seconds between measurements
  
  # Amp adjustment settings - control how aggressively charging responds to conditions
  amp_adjustments:
    increase_step: 1          # Amps to increase when conditions allow more charging
    decrease_step: 2          # Amps to decrease when limiting is needed

# Tesla Integration
tesla:
  enabled: false
  
  # Fleet API Authentication (required)
  client_id: null               # Tesla Fleet API client ID
  client_secret: null           # Tesla Fleet API client secret  
  refresh_token: null           # Tesla API refresh token
  vehicle_id: null              # Tesla vehicle ID (numeric)
  vehicle_tag: null             # Tesla vehicle tag/VIN
  vin: null                     # Tesla VIN (required for signed commands)
  
  # TVCP (Tesla Vehicle Command Protocol) - Required for modern vehicles
  private_key: "data/tesla-reg-keys/private-key.pem"  # Path to private key for signed commands
  
  # Charging Configuration
  min_charging_amps: 5         # Minimum charging current
  max_charging_amps: 32        # Maximum charging current
  charging_voltage: 200        # EV charging voltage
  
  # Optional: Advanced settings
  region: "auto"               # Tesla region: "auto", "na", "eu", "cn"
  command_rate_limit: 5        # Commands per minute
  timeout: 10                  # Request timeout in seconds

# Logging Configuration
logging:
  level: "INFO"                # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "ecolit.log"           # Log file path
  max_size: "10MB"             # Maximum log file size before rotation
  backup_count: 5              # Number of rotated log files to keep

# Example configurations:

# Discovery Mode (find devices automatically):
# network:
#   scan_ranges: []
# devices:
#   required: []

# Production Mode (validate specific devices):
# devices:
#   required:
#     - name: "Solar Inverter"
#       ip: "192.168.0.2"
#       type: "solar"
#       eojgc: 0x02
#       eojcc: 0x79
#       instance: 31
#     - name: "Storage Battery"
#       ip: "192.168.0.2"
#       type: "battery"
#       eojgc: 0x02
#       eojcc: 0x7D
#       instance: 31

# EV Charging enabled with HURRY policy:
# ev_charging:
#   enabled: true
#   policy: "hurry"
#   max_amps: 16