[project]
name = "energy-analysis"
version = "0.1.0"
description = "Energy data analysis for Tesla charging optimization"
dependencies = [
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "matplotlib>=3.7.0",
    "seaborn>=0.12.0",
    "jupyter>=1.0.0",
]

[tool.uv]
dev-dependencies = []